# Generated by Django 5.0.7 on 2024-07-29 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('calorias', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
            },
        ),
        migrations.CreateModel(
            name='AtividadeRelaxamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Atividade Relaxamento',
                'verbose_name_plural': 'Atividade Relaxamento',
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrição', models.CharField(max_length=100)),
                ('dose', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
            },
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Refeição',
                'verbose_name_plural': 'Refeição',
            },
        ),
        migrations.CreateModel(
            name='TipoAtividadeFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo Atividade Fisíca',
                'verbose_name_plural': 'Tipo Atividade Fisíca',
            },
        ),
        migrations.RemoveField(
            model_name='atividadealimentar',
            name='cardapio',
        ),
        migrations.AlterField(
            model_name='saude',
            name='relaxamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.atividaderelaxamento'),
        ),
        migrations.AlterField(
            model_name='saude',
            name='medicamentos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.medicamento'),
        ),
        migrations.AlterField(
            model_name='atividadealimentar',
            name='refeicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.refeicao'),
        ),
        migrations.AlterField(
            model_name='atividadefisica',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoatividadefisica'),
        ),
    ]
