# Generated by Django 5.0.7 on 2024-07-29 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alimento_atividaderelaxamento_medicamento_refeicao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alimento',
            options={'verbose_name': 'Alimento', 'verbose_name_plural': 'Alimentos'},
        ),
    ]
